name: Servercore Container Build and Push

on:
  push:
   branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-2022
    env:
      RUNNER_VERSION: 2.311.0

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Dockerfile
        run: docker build -t ghcr.io/dbaur/win-action-runner:${{ github.ref_name }} --build-arg RUNNER_VERSION=${{env.RUNNER_VERSION}} .

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/dbaur/win-action-runner:${{ github.ref_name }}